### ISSUE TITLE
모달창

### ISSUE THREAD

**Issue by vnfdusdl** [duck-map-project/duck-map-fe#138]
## Description

그룹, 아티스트, 카테고리 등록 시 사용되는 모달창

## To-do

- [x] 공통 모달
- [x] 그룹 등록 모달
- [x] 아티스트 등록 모달
- [x] 이벤트 카테고리 등록 모달
- [x] 아티스트 타입 등록 모달

**Comment by vnfdusdl** [comment]
완료했습니다!
