### ISSUE TITLE
드롭다운 UI 변경

### ISSUE THREAD

**Issue by vnfdusdl** [duck-map-project/duck-map-fe#153]
## Description

디자인 변경에 따른 드롭다운 UI 변경 필요

## To-do

- [x] 리스트 사이의 가로선 없애기
- [x] 용도별 icon 존재 유무
- [x] 하이라이트 색깔 변경
