### ISSUE TITLE
관리자페이지 추가 UI 및 기능

### ISSUE THREAD

**Issue by vnfdusdl** [duck-map-project/duck-map-fe#191]
## Description

관리자페이지 내 추가된 UI와 이에 따른 기능 추가

## To-do

- [x] 카테고리 목록 조회 UI
- [x] 아티스트 타입 목록 조회 UI
- [x] 그룹 아티스트 수정
- [x] 아티스트 수정
- [x] 카테고리 수정
- [x] 카테고리 삭제
- [x] 아티스트 타입 수정
- [x] 아티스트 타입 삭제
