### ISSUE TITLE
북마크 내 이벤트, 나의 이벤트 조회/수정/삭제, 상세 이벤트 페이지로 이동

### ISSUE THREAD

**Issue by vnfdusdl** [duck-map-project/duck-map-fe#195]
## Description

마이페이지 내에 이벤트 관련 기능 

## To-do

- [x] 북마크 내 이벤트 삭제
- [x] 나의 이벤트 수정
- [x] 나의 이벤트 삭제
- [x] 이벤트 리스트 클릭 시 상세 이벤트 페이지로 이동
